## Settings
title: 你能看到这就是我们的缘分。别走！多看两眼这没准有你想要的
owner: "gongdaowei"
url: "https://dawell.me/"
baseurl: "/pages/index.html"
permalink: /:title/
description: ""
markdown:
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "18610631724@163.com"
github: "gongdaowei/gongdaowei.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: ""
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√**I LOVE 娟娟**"